Поддержка телефонии
mesilov/bitrix24-php-sdk pull request #297
Opened 2022-06-29 14:01 UTC by KarlsonComplete

# Ожидания по PR

## Документация

- [x] написана статья для новичков «Как сделать локальное приложение с использованием SDK»
- [x] написана статья для новичков «Как добавить новый скоуп в SDK»
- [x] проанализированы [типовые сценарии](https://dev.1c-bitrix.ru/rest_help/scope_telephony/telephony/example.php) и написана дока с описанием тестового приложения 

## Функционал

- [x] в скоупе телефония добавлены сервисы по работе с нужными ручками
- [ ] в скоупе телефония добавлены события унаследованные от `Bitrix24\SDK\Application\Requests\AbstractRequest`

## Тесты
- [x] где возможно - написаны интеграционные тесты

2022-06-29 14:06 UTC, mesilov commented
Метки развесил

2022-07-13 11:54 UTC, mesilov commented on tests/Integration/Services/Telephony/Service/ExternalCallTest.php
> +            'FAILED_REASON' => '',
Отдельное перечисление с человеческими названиями

2022-07-14 12:28 UTC, mesilov requested changes

2022-07-15 09:19 UTC, mesilov requested changes

2022-07-15 09:19 UTC, mesilov commented on src/Services/Telephony/Common/CallType.php
> +class CallType
Посмотри пожалуйста на CrmEntityType и сделай аналогично

2022-07-15 09:19 UTC, mesilov commented on src/Services/Telephony/Common/StatusCodeInterface.php
> +interface StatusCodeInterface
Сделай пожалуйста по аналогии 1:1 с https://github.com/php-fig/http-message-util/blob/master/src/StatusCodeInterface.php

Список кодов и наименований взять тут — https://en.wikipedia.org/wiki/List_of_SIP_response_codes

2022-07-15 09:20 UTC, KarlsonComplete commented on src/Services/Telephony/Common/StatusCodeInterface.php
> +interface StatusCodeInterface
да, окей

2022-07-15 11:09 UTC, KarlsonComplete commented on src/Services/Telephony/Common/StatusCodeInterface.php
> +interface StatusCodeInterface
В википедии нету статуса 304(я взял из файла который ты скинул), а также в доках битрикса и википедии не сходятся некоторые названия. Что делать со статусом 603-S Call is cancelled. ?OTHER Unidentified ?

2022-07-15 11:29 UTC, KarlsonComplete commented on src/Services/Telephony/Common/CallType.php
> +class CallType
Готово

2022-07-15 14:11 UTC, KarlsonComplete commented on src/Services/Telephony/Common/StatusCodeInterface.php
> +interface StatusCodeInterface
Добавил все статусы из википедии.

2022-07-22 08:27 UTC, mesilov requested changes

2022-07-22 08:27 UTC, mesilov commented on src/Services/Telephony/Result/ExternalLineDeleteResult.php
> +class ExternalLineDeleteResult extends AbstractResult
А что тут возвращается? Может можно возвращать Bitrix24\SDK\Core\Result\DeletedItemResult?

2022-07-22 08:27 UTC, mesilov commented on src/Services/Telephony/Service/ExternalCall.php
> +    public function attachRecord(string $callId, string $fileName, string $fileContent, ?string $recordUrl = null): ExternalCallRecordResult
переименуй переменную в $base64encodedFileContent

2022-07-22 08:27 UTC, mesilov commented on src/Services/Telephony/Service/ExternalLine.php
> +    public function add(string $lineNumber , string $nameLine): ExternalLineAddResult
переименуй в $lineName

2022-07-22 08:27 UTC, mesilov commented on src/Services/Telephony/Service/ExternalLine.php
> +    public function update(string $lineNumber, string $nameLine): ExternalLineUpdateResult
переименуй в $newLineName

2022-07-22 08:27 UTC, mesilov commented on tests/Integration/Services/Telephony/Service/ExternalCallTest.php
> +    private function getFileInBase64(): string
Я не вижу в коммите в тестах самого файла, ты его не закомитил

2022-07-22 08:27 UTC, mesilov commented on CHANGELOG.md
> +* fix error in `NetworkTimingParser`, [error in NetworkTimingsErrorInfo](https://github.com/mesilov/bitrix24-php-sdk/issues/277)
Добавь в блок  Added строку add new scope Telephony

2022-07-22 08:27 UTC, mesilov commented on CHANGELOG.md
> +* fix error in `NetworkTimingParser`, [error in NetworkTimingsErrorInfo](https://github.com/mesilov/bitrix24-php-sdk/issues/277)
Добавь в блок Added строку, что ты добавил поддержку денег c помощью библиотеки PhpMoney (ссылка на репозиторий)

2022-07-22 08:27 UTC, mesilov commented on README.md
>  ### Tests
Продублируй заголовок Тесты на русском и переведи эти два предложения

2022-07-22 10:49 UTC, KarlsonComplete commented on tests/Integration/Services/Telephony/Service/ExternalCallTest.php
> +            'CRM_ENTITY_TYPE' => 'LEAD',
готово

2022-07-22 10:49 UTC, KarlsonComplete commented on tests/Integration/Services/Telephony/Service/ExternalCallTest.php
> +            'STATUS_CODE' => 'VI_STATUS_200',
готово

2022-07-22 10:50 UTC, KarlsonComplete commented on tests/Integration/Services/Telephony/Service/ExternalCallTest.php
> +    public function testSearchCrmEntities():void
готово

2022-07-22 10:50 UTC, KarlsonComplete commented on src/Services/Telephony/Common/CurrencyList.php
> +class CurrencyList
готово

2022-07-22 10:52 UTC, KarlsonComplete commented on src/Services/Telephony/Service/ExternalLine.php
> +    public function update(string $lineNumber, string $nameLine): ExternalLineUpdateResult
готово

2022-07-22 10:58 UTC, KarlsonComplete commented on tests/Integration/Services/Telephony/Service/ExternalCallTest.php
> +    private function getFileInBase64(): string
Готово

2022-07-22 10:58 UTC, KarlsonComplete commented on CHANGELOG.md
> +* fix error in `NetworkTimingParser`, [error in NetworkTimingsErrorInfo](https://github.com/mesilov/bitrix24-php-sdk/issues/277)
Готово

2022-07-22 11:00 UTC, KarlsonComplete commented on CHANGELOG.md
> +* fix error in `NetworkTimingParser`, [error in NetworkTimingsErrorInfo](https://github.com/mesilov/bitrix24-php-sdk/issues/277)
Готово

2022-07-22 11:17 UTC, KarlsonComplete commented on README.md
>  ### Tests
готово

2022-07-22 12:26 UTC, merged