237 serializer test
mesilov/bitrix24-php-sdk pull request #308
Opened 2022-09-02 06:05 UTC by KarlsonComplete

Занимаюсь добавлением поддержки phpmoney как базового типа для денег

2022-09-10 12:57 UTC, mesilov requested changes

2022-09-10 12:57 UTC, mesilov commented on src/Infrastructure/HttpClient/TransportLayer/NetworkTimingsParser.php
> +            'namelookup_time'    => $httpClientResponseInfo['namelookup_time'],
влей пожалуйста актуальный мастер в свою ветку

2022-09-10 12:57 UTC, mesilov commented on src/Services/CRM/Deal/Result/DealProductRowItemResult.php
> +    public function __get($offset)
похоже, что этот метод лишний, т.к. он ничего не делает

2022-09-10 12:57 UTC, mesilov commented on composer.json
> +    "symfony/serializer": "6.*||^6.1",
пока не используем сериалайзер

2022-09-10 12:57 UTC, mesilov commented on composer.json
> +    "symfony/property-access": "6.* || 6.1.*",
пока тоже не используем

2022-09-10 12:57 UTC, mesilov commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +        $deal_test_id = $data['result']['deal']['ID'];
Сделай var_dump и посмотри, что возвращается, там будет ISO-код валюты.
Т.е. что бы сделать объект Curency его его нужно будет передать в конструктор.

2022-09-10 12:57 UTC, mesilov commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +        return new DealProductRowItemsResult($deal_test_id,$currency);
посмотри на сигнатуру конструктора Bitrix24\SDK\Core\Result\AbstractResult и результат core->call

2022-09-10 13:56 UTC, KarlsonComplete commented on composer.json
> +    "symfony/routing": "^4.4|^5.3|^6.0",
-готово

2022-09-10 13:56 UTC, KarlsonComplete commented on tests/Integration/Services/MixedTest/MixedTest.php
> +<?php
-готово

2022-09-10 13:56 UTC, KarlsonComplete commented on tests/Unit/Services/TestPerson/Person.php
> +<?php
готово

2022-09-10 13:56 UTC, KarlsonComplete commented on tests/Unit/Services/TestPerson/PersonNormalizer.php
> +<?php
готово

2022-09-10 13:56 UTC, KarlsonComplete commented on tests/Unit/Services/TestPerson/PersonTest.php
> +<?php
готово

2022-09-10 14:26 UTC, KarlsonComplete commented on composer.json
> +    "symfony/property-access": "6.* || 6.1.*",
готово

2022-09-10 14:26 UTC, KarlsonComplete commented on composer.json
> +    "symfony/serializer": "6.*||^6.1",
готово

2022-09-10 14:26 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Result/DealProductRowItemResult.php
> +    public function __get($offset)
готово

2022-09-10 14:34 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +        return new DealProductRowItemsResult($deal_test_id,$currency);
готово

2022-09-10 14:34 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +        $deal_test_id = $data['result']['deal']['ID'];
готово

2022-10-19 15:30 UTC, mesilov reviewed
Отревьюил, жду правок

2022-10-19 15:30 UTC, mesilov commented on tests/Integration/Services/CRM/Deal/Service/DealProductRowsTest.php
> +use Money\Money;
@KarlsonComplete а сейчас?

2022-10-19 15:30 UTC, mesilov commented on src/Services/CRM/Common/Result/AbstractCrmItem.php
> +                return null;
@KarlsonComplete

2022-10-19 15:30 UTC, mesilov commented on src/Services/CRM/Deal/Result/DealProductRowItemsResult.php
> +        foreach ($this->getCoreResponse()->getResponseData()->getResult()['result']['rows'] as $productRow) {
@KarlsonComplete

2022-10-19 19:25 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Result/DealProductRowItemsResult.php
> +        foreach ($this->getCoreResponse()->getResponseData()->getResult()['result']['rows'] as $productRow) {
Вообщем у меня с этим сейчас возникли проблемы , но я вроде бы пофиксил это добавив дополнительное условие. Проблема была в том что наш метод очень умный getSuperSuperSmart(get). И если мы принимаем только айдишник сделки, то у нас выполняется batch запрос в котором мы возвращаем саму сделку и строку товара, это все у нас записывается в переменную $res. Потом мы ее добавляем в наш объект DealProductRowItemsResult. После чего нам приходится дополнительно указывать [result][rows] , так как есть еще выбор выбрать [result][deal]. А вот если мы указываем в нашем методе и айдишник и валюту , то тогда в DealProductRowItemsResult у нас приходит лишь один запрос с одним массивом и нам не нужно указывать [result][rows].

2022-10-19 19:33 UTC, KarlsonComplete commented on src/Services/CRM/Common/Result/AbstractCrmItem.php
> +                return null;
готово

2022-10-19 19:33 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +    public function getStupid(int $dealId, Currency $currency): DealProductRowItemsResult
готово

2022-10-19 19:33 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +    public function getSuperSmart(int $dealId): DealProductRowItemsResult
готово

2022-10-19 19:33 UTC, KarlsonComplete commented on src/Services/CRM/Deal/Service/DealProductRows.php
> +    public function getSuperSuperSmart(int $dealId, Currency $currency = null): DealProductRowItemsResult
готово

2022-10-19 19:34 UTC, KarlsonComplete commented on tests/Integration/Services/CRM/Deal/Service/DealProductRowsTest.php
> +use Money\Money;
ну тесты я делаю не очень , надеюсь готово)

2022-10-31 10:41 UTC, merged